### PR TITLE
Authentication - PR For Review

### PR DESCRIPTION
**Pull request by dibdas**
In this project, We built an exclusive clubhouse where  members can write anonymous posts. Inside the clubhouse, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @dibdas and @udberg   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] Please fix your linter errors. This shows how professional your project is. 
- [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)). Right now, I can only see the text, both as a guest and a signed-in user.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @dibdas and @udberg   ! :wave: :wave:

#### Good job fixing the linter errors! :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).

- It seems while you were trying to implement this requirement, you broke something in your code, cause now, I can only see all the posts when I'm signed in, and I still can't see the author. 
- I also cannot edit my post, as there are no links to edit or links to the show page.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 

Hello, @dibdas and @udberg Very nice work submitting the project. Also, good work making the improvements. However, the problem discussed above is still there. ⬇️ 

- [x] When I create a post is should be able to see the author if you check below ⬇️ the author name is not visible 

signed_in_can_see_author_requirement

- [x] Also when I sign out, I should also be able to see the posts but not the author. Kindly fix these two issues ⬇️ 

guest_can_see_only_posts_requirement (1)

- [x] Also your commit messages should follow best practices. For example, you should capitalize your commits. 
Read more on this [here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules)

### if you have any question reach me on slack @peterrobert

### HAPPY CODING 💻

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Udberg John & Dibyendu Das** 
Good job with the improvements for this project :muscle:  :muscle:
There some details to improve before you can go ahead:

- [x] When I go to the root of your project the next error appears: 

- [x] Add a screenshot in your README file
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by oloomoses — APPROVED** [review]
# Congratulation! Project Approved :muscle: :tada: :clap: 
You have done a great job and the project meets all the minimum requirements.
Feel free to merge and close this pull request.
I wish you the best in your next project. See you at the top
## Slack [Oloo Moses]

**Pull request merged**
